---
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  imageRegistry: 'quay.io/powercloud'
  certificateRotateStrategy: {}
  configuration:
    developerConfiguration:
      featureGates:
        - Root
  customizeComponents: {}
  imagePullPolicy: Always
  workloadUpdateStrategy: {}

