apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: testvmfedora
spec:
  runStrategy: Manual
  template:
    metadata:
      labels:
        kubevirt.io/size: large
        kubevirt.io/domain: testvm
    spec:
      architecture: ppc64le
      domain:
        features:
          acpi:
            enabled: false
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            masquerade: {}
        machine:
          type: pseries
        cpu:
          model: host-passthrough
        resources:
          requests:
            memory: 4G
      networks:
      - name: default
        pod: {}
      terminationGracePeriodSeconds: 0
      accessCredentials:
      - sshPublicKey:
          source:
            secret:
              secretName: my-pub-key
          propagationMethod:
            qemuGuestAgent:
              users:
              - fedora
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/powercloud/cirros-container-disk-demo:v1.1.1-fedora-cloud
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              password: fedora
              chpasswd: { expire: False }
